### PR TITLE
feat: introduce and support --minify parameter in hugo

### PR DESCRIPTION
**Pull request by MrCSharp22**
This PR is to support the --minify parameter in hugo which generates minified html,css, and js assets.

### CODE REVIEW

**Comment by giuliov** [comment]
Please be patient, I need some time to catch up with this project.

**Comment by MrCSharp22** [comment]
That's ok mate, no rush.

**Comment by appieschot** [comment]
Any plans on finalizing this? Would love to have this in. If you want I am more than happy to help speed things up.

**Comment by pavelstoev-lci** [comment]
@appieschot  @MrCSharp22 
Useful PR. As a hack while we wait, add " --minify" to destination argument - worked like a charm for me.

https://github.com/giuliov/hugo-vsts-extension/blob/f4512a1623903b9cc41811961221c040319b561e/hugo-task/Invoke-Hugo.ps1#L25

**Pull request closed without merging**
